# version: '3.8'

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file: .env
    restart: on-failure
    networks:
      - inception

    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    env_file: .env
    restart: on-failure
    depends_on:
        - wordpress
    ports:
      - 443:443
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    env_file:
      - .env
    depends_on:
        - mariadb
    ports:
      - 9000:9000
    restart: on-failure
    networks:
      - inception