# version: '3.8'

networks:
  inception:
    name: inception

volumes:
  wordpress:
   driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
  mariadb:
   driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file: .env
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    env_file:
      - .env
    depends_on:
        - mariadb
    ports:
      - 9000:9000
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    env_file: .env
    restart: on-failure
    depends_on:
        - wordpress
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    