# version: '3.8'

networks:
  inception:
    name: inception

volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
    
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb

  redis:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/redis

secrets:
  mariadb_password:
    file: ../secrets/mariadb_password
  mariadb_root_password:
    file: ../secrets/mariadb_root_password
  wp_password:
    file: ../secrets/wp_password
  wp_user2_password:
    file: ../secrets/wp_user2_password

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file: .env
    secrets:
      - mariadb_password
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - /home/$USER/data/mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    env_file:
      - .env
    secrets:
      - wp_password
      - wp_user2_password
      - mariadb_password
      - mariadb_root_password
    depends_on:
        - mariadb
        - redis
    ports:
      - 9000:9000
    restart: on-failure
    networks:
      - inception
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    env_file: .env
    restart: on-failure
    depends_on:
        - wordpress
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - /home/$USER/data/wordpress:/var/www/html

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - inception
    volumes:
      - /home/$USER/data/redis:/data